easy_admin:

    site_name: 'ADMIN <em style="font-size: 80%;">Base Manager</em>'

    list:
        max_results: 20
        actions:
            - { name: 'show', icon: 'search' }
            - { name: 'edit', icon: 'pencil' }
            - { name: 'delete', icon: 'trash' }
            - { name: 'search', icon: 'search' }

    design:
        color_scheme: 'light'
        form_theme: 'vertical'

    entities:
        User:
            class: App\Entity\User

        Team:
            class: App\Entity\Team
